export const CREATE_EVENT = "CREATE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const DELETE_EVENT = "DELETE_EVENT";
export const VIEW_SELECTED_EVENT = "VIEW_SELECTED_EVENT";
export const ON_CANCEL_CLICK = "ON_CANCEL_CLICK";
export const CREATE_EVENT_BUTTON = "CREATE_EVENT_BUTTON";
